### ISSUE TITLE
allow +* or other regex stuff

### ISSUE THREAD

**Issue by MrMineDe** [MrMineDe/pakt#25]

**Comment by MrMineDe** [comment]
We have to detect regex, so we cant create a category file with random regex as name. Than we only work on the existing files

**Comment by MrMineDe** [comment]
Maybe it's a good idea to have a different character than + for this regex stuff?

**Comment by hiimsergey** [comment]
`+*` would be a good idea but do we need other regex capabilities? What could be real-world uses of that?
Would it be possible to just reserve `+*` itself for the action?
I'd like `+` too, the question is how to implement that.

**Comment by MrMineDe** [comment]
In my head implementing the regex stuff is not very complicated and rather straight forward, but i'll test it. If its complicated i'd also opt to just support +*. I dont really have a real world use case, but it seems like a nice to have feature nontheless, if it's not complicated, but idk... + can be easily checked by checking if $A is 1 char long

**Comment by hiimsergey** [comment]
It looks like it‘s a low priority issue not contributing to core functionality. If you struggle with the implementation, then at least let‘s postpone it.

**Comment by MrMineDe** [comment]
fair. assigned p4

**Comment by hiimsergey** [comment]
Solved with `++` instead of `+*` because the shell struggles with it.
It also works with adding packages, it just puts the pkgs into all catfiles you currently have. :)
