### ISSUE TITLE
Decide if we want a short help flag like -h and overwrite the pacman flag

### ISSUE THREAD

**Issue by MrMineDe** [MrMineDe/pakt#29]

**Comment by MrMineDe** [comment]
I'm against it, as it removes compatibility. @hiimsergey?

**Comment by hiimsergey** [comment]
No one would want to look up pacman help using pakt, so I'd keep --help. You decice what to do with -h.

**Comment by MrMineDe** [comment]
I think you would try to get the pacman help page maybe, as I would personally alias pacman to pakt and use it as a 1 to 1 replacement. I think --pakt-help could be a good alternative? Also I would just ditch -h and let pacman handle that flag

**Comment by hiimsergey** [comment]
- we keep it that way and you call the help page with ˋ/bin/pacman —helpˋ
- we get rid of pakt‘s help page entirely and move everything to the man page

I really don‘t like the —pakt-help idea 🤷‍♂️. Choose either.

**Comment by MrMineDe** [comment]
fair. lets do 2.

**Comment by MrMineDe** [comment]
Print an info like: "printing pacman help page, if you want the help for pakt, see man pakt"
When we detect --help or -h

**Comment by MrMineDe** [comment]
#23 needs to be solved, in order to make progress here

**Comment by MrMineDe** [comment]
solved by 518dab0918c12c8d64b45e0c0acd8b70495c5996
