### ISSUE TITLE
Decide what the program should do on nonexisting config

### ISSUE THREAD

**Issue by MrMineDe** [MrMineDe/pakt#31]

**Comment by MrMineDe** [comment]
1. We could provide a default config inside the script to load
2. We could source the default config, that is hopefully on the system
3. We could copy the default config, that is hopefully on the system to a correct location and source it

**Comment by MrMineDe** [comment]
@hiimsergey ?

**Comment by hiimsergey** [comment]
I'd say that pakt sources the default config (/etc/pakt.conf or /usr/share/pakt.conf) if no user config exists.
If the default config doesn't exist, we either

1. let the source command throw an error:

```
.: Error encountered while sourcing file '/etc/pakt.conf':
.: No such file or directory
```

2. write our own message by performing a check in the script.

I'm for 1.
