### ISSUE TITLE
Decide what the program should do about partial configs/if we should even allow it

### ISSUE THREAD

**Issue by MrMineDe** [MrMineDe/pakt#32]

**Comment by MrMineDe** [comment]
Related to #31

**Comment by hiimsergey** [comment]
Writing `set -u`  enables strict mode, meaning the script throws errors when dealing with unbound variables.
But the following block,

```sh
if [ -z "$PAKT_CONF_PATH" ]; then
	PAKT_CONF_PATH=$HOME/.config/pakt
fi
```

causes an error because of it but can be easily fixed by appending a minus:

```sh
if [ -z "${PAKT_CONF_PATH-}" ]; then
	PAKT_CONF_PATH=$HOME/.config/pakt
fi
```

**Comment by MrMineDe** [comment]
Looks good, but the script would not exit after erroring as I understand it. That would make it basically useless. Also there might be confusion about the error message, as its not very concise about the root of the problem.

I think a better way would be checking every variable possibly defined in the config like you did above and if its not set just set to a default. It adds a bit of boilerplate, but is worth it imo

**Comment by hiimsergey** [comment]
_sigh_

**Comment by hiimsergey** [comment]
Won the bet.
Closing this.
