### ISSUE TITLE
support all pacman commands (subcommands with more arguments are not supported, commands after the first argument are interpreted as package)

### ISSUE THREAD

**Issue by MrMineDe** [MrMineDe/pakt#5]

**Comment by MrMineDe** [comment]
Maybe add a variable like CMD_ARG_2_STRINGS but with a better name, where one can add all the arguments of the package manager that need 2 strings. e.g. -f FILEPATH would be one. right now -f would get caught, but FILEPATH would be a package again. in the variable you would define CMD_ARG_2_STRINGS="-f -T --arg"

**Comment by hiimsergey** [comment]
jokes on you, c2765fb9aa9cabac0866c2141b2ab8ba7f8b4fa3

**Comment by MrMineDe** [comment]
not solved

**Comment by MrMineDe** [comment]
still not solved :skull:

**Comment by hiimsergey** [comment]
Closed it accidentally
